//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLoadSave.DBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DataModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private int AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name LoadDBResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDB", ReplyAction="*")]
        DBLoadSave.DBService.LoadDBResponse LoadDB(DBLoadSave.DBService.LoadDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDB", ReplyAction="*")]
        System.Threading.Tasks.Task<DBLoadSave.DBService.LoadDBResponse> LoadDBAsync(DBLoadSave.DBService.LoadDBRequest request);
        
        // CODEGEN: Generating message contract since element name _fName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDB", ReplyAction="*")]
        DBLoadSave.DBService.SaveDBResponse SaveDB(DBLoadSave.DBService.SaveDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDB", ReplyAction="*")]
        System.Threading.Tasks.Task<DBLoadSave.DBService.SaveDBResponse> SaveDBAsync(DBLoadSave.DBService.SaveDBRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadDB", Namespace="http://tempuri.org/", Order=0)]
        public DBLoadSave.DBService.LoadDBRequestBody Body;
        
        public LoadDBRequest() {
        }
        
        public LoadDBRequest(DBLoadSave.DBService.LoadDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadDBRequestBody {
        
        public LoadDBRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public DBLoadSave.DBService.LoadDBResponseBody Body;
        
        public LoadDBResponse() {
        }
        
        public LoadDBResponse(DBLoadSave.DBService.LoadDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DBLoadSave.DBService.DataModel[] LoadDBResult;
        
        public LoadDBResponseBody() {
        }
        
        public LoadDBResponseBody(DBLoadSave.DBService.DataModel[] LoadDBResult) {
            this.LoadDBResult = LoadDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDB", Namespace="http://tempuri.org/", Order=0)]
        public DBLoadSave.DBService.SaveDBRequestBody Body;
        
        public SaveDBRequest() {
        }
        
        public SaveDBRequest(DBLoadSave.DBService.SaveDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DBLoadSave.DBService.ArrayOfString _fName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DBLoadSave.DBService.ArrayOfString _lName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DBLoadSave.DBService.ArrayOfInt _age;
        
        public SaveDBRequestBody() {
        }
        
        public SaveDBRequestBody(DBLoadSave.DBService.ArrayOfString _fName, DBLoadSave.DBService.ArrayOfString _lName, DBLoadSave.DBService.ArrayOfInt _age) {
            this._fName = _fName;
            this._lName = _lName;
            this._age = _age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public DBLoadSave.DBService.SaveDBResponseBody Body;
        
        public SaveDBResponse() {
        }
        
        public SaveDBResponse(DBLoadSave.DBService.SaveDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveDBResponseBody {
        
        public SaveDBResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DBLoadSave.DBService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DBLoadSave.DBService.WebService1Soap>, DBLoadSave.DBService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBLoadSave.DBService.LoadDBResponse DBLoadSave.DBService.WebService1Soap.LoadDB(DBLoadSave.DBService.LoadDBRequest request) {
            return base.Channel.LoadDB(request);
        }
        
        public DBLoadSave.DBService.DataModel[] LoadDB() {
            DBLoadSave.DBService.LoadDBRequest inValue = new DBLoadSave.DBService.LoadDBRequest();
            inValue.Body = new DBLoadSave.DBService.LoadDBRequestBody();
            DBLoadSave.DBService.LoadDBResponse retVal = ((DBLoadSave.DBService.WebService1Soap)(this)).LoadDB(inValue);
            return retVal.Body.LoadDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DBLoadSave.DBService.LoadDBResponse> DBLoadSave.DBService.WebService1Soap.LoadDBAsync(DBLoadSave.DBService.LoadDBRequest request) {
            return base.Channel.LoadDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<DBLoadSave.DBService.LoadDBResponse> LoadDBAsync() {
            DBLoadSave.DBService.LoadDBRequest inValue = new DBLoadSave.DBService.LoadDBRequest();
            inValue.Body = new DBLoadSave.DBService.LoadDBRequestBody();
            return ((DBLoadSave.DBService.WebService1Soap)(this)).LoadDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBLoadSave.DBService.SaveDBResponse DBLoadSave.DBService.WebService1Soap.SaveDB(DBLoadSave.DBService.SaveDBRequest request) {
            return base.Channel.SaveDB(request);
        }
        
        public void SaveDB(DBLoadSave.DBService.ArrayOfString _fName, DBLoadSave.DBService.ArrayOfString _lName, DBLoadSave.DBService.ArrayOfInt _age) {
            DBLoadSave.DBService.SaveDBRequest inValue = new DBLoadSave.DBService.SaveDBRequest();
            inValue.Body = new DBLoadSave.DBService.SaveDBRequestBody();
            inValue.Body._fName = _fName;
            inValue.Body._lName = _lName;
            inValue.Body._age = _age;
            DBLoadSave.DBService.SaveDBResponse retVal = ((DBLoadSave.DBService.WebService1Soap)(this)).SaveDB(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DBLoadSave.DBService.SaveDBResponse> DBLoadSave.DBService.WebService1Soap.SaveDBAsync(DBLoadSave.DBService.SaveDBRequest request) {
            return base.Channel.SaveDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<DBLoadSave.DBService.SaveDBResponse> SaveDBAsync(DBLoadSave.DBService.ArrayOfString _fName, DBLoadSave.DBService.ArrayOfString _lName, DBLoadSave.DBService.ArrayOfInt _age) {
            DBLoadSave.DBService.SaveDBRequest inValue = new DBLoadSave.DBService.SaveDBRequest();
            inValue.Body = new DBLoadSave.DBService.SaveDBRequestBody();
            inValue.Body._fName = _fName;
            inValue.Body._lName = _lName;
            inValue.Body._age = _age;
            return ((DBLoadSave.DBService.WebService1Soap)(this)).SaveDBAsync(inValue);
        }
    }
}
